package com.example.cashroyale.Models

import android.os.Parcelable
import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index
import androidx.room.PrimaryKey
import kotlinx.parcelize.Parcelize

/**
 * Represents the monthly financial goals set by a user.
 * Uses Room annotations for database mapping and relationships.
 * Implements [Parcelable] for easy data passing.
 */
@Parcelize
@Entity(
    tableName = "monthly_goals", // The name of the database table
    foreignKeys = [
        ForeignKey(
            entity = User::class, // The related entity
            parentColumns = ["email"], // The primary key column in the User entity
            childColumns = ["userId"], // The foreign key column in this entity
            onDelete = ForeignKey.CASCADE // What happens to goals if the associated user is deleted
        )
    ],
    indices = [Index("userId")] // An index to speed up queries based on userId
)
data class MonthlyGoals(
    /**
     * Unique identifier for the monthly goal.
     * Auto-generated by the database.
     */
    @PrimaryKey(autoGenerate = true) val goalId: Int = 0,

    /**
     * The ID of the user who set this monthly goal.
     * This is a foreign key referencing the `email` column of the `User` table.
     */
    val userId: String, // Should match the type of User's primary key (likely String for email)

    /**
     * The maximum budget amount the user aims to stay within for the month.
     */
    val maxGoalAmount: Double,

    /**
     * The minimum budget amount the user expects to spend for the month.
     */
    val minGoalAmount: Double,

    /**
     * Indicates whether the user has actively set these goals.
     * Defaults to false.
     */
    val goalSet: Boolean = false
): Parcelable